# Generated by Django 3.2.4 on 2021-07-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_dummy_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dummy_date',
        ),
    ]
