# Generated by Django 3.2.3 on 2021-07-01 21:25

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'base_manager_name': 'products', 'ordering': ('-created_at',)},
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('products', django.db.models.manager.Manager()),
            ],
        ),
    ]
