# Generated by Django 3.2.3 on 2021-07-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210701_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
